### ISSUE TITLE
Failed when enabling device

### ISSUE THREAD

**Issue by pete-mcneill** [Cynary/sunshine-virtual-monitor#4] opened 2024-08-24 20:39 UTC
Hitting the below error when the script hits this line of code, running it in isolation has the same error:

`pnputil /enable-device /deviceid root\iddsampledriver`

`Microsoft PnP Utility

PNPUTIL [/add-driver <...> | /delete-driver <...> |
         /export-driver <...> | /enum-drivers |
         /enum-devices [<...>] | /enum-interfaces [<...>] |
         /disable-device <...> | /enable-device <...> |
         /restart-device <...> | /remove-device <...> |
         /scan-devices [<...>] | /?]

Commands:

  /?

    Show usage screen.

  /enable-device <instance ID> [/reboot]

    Enable devices on the system.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Enable device:
        pnputil /enable-device "USB\VID_045E&PID_00DB\6&870CE29&0&1"`

**Comment by Cynary** [comment] 2024-09-07 19:54
Did this happen after a reboot? It may be a repeat of #6

**Comment by Cynary** [comment] 2024-09-08 03:46
Hi @pete-mcneill please check if the issue is resolved with the newest changes.

**Comment by Cynary** [comment] 2024-09-25 05:06
Closing, assuming the recent changes fix the issue - feel free to open a new issue if not.

**Closed by Cynary** 2024-09-25 05:06 UTC
