### ISSUE TITLE
Fails to Disable All Other Displays

### ISSUE THREAD

**Issue by gercamjr** [Cynary/sunshine-virtual-monitor#9] opened 2024-09-14 01:55 UTC
I created a Virtual Display successfully and then disabled it per your instructions. I added the Global start up and tear down commands in the Sunshine config. I then connect to the Sunshine host through my TV's Moonlight client and try to start the Playnite app for example, and the Moonlight client displays a popup saying it is starting Playnite...but it just hangs and never actually connects. So I review the Sunshine logs and I see the following:

```
[2024:09:13:20:42:40]: Info: Found H.264 encoder: h264_amf [amdvce]
[2024:09:13:20:42:40]: Info: Found HEVC encoder: hevc_amf [amdvce]
[2024:09:13:20:42:40]: Info: Executing Do Cmd: [cmd /C powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\CLI\sunshine-virtual-monitor-main\setup_sunvdm.ps1" %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > "C:\CLI\sunshine-virtual-monitor-main\sunvdm.log" 2>&1]
[2024:09:13:20:42:40]: Info: cmd /C powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\CLI\sunshine-virtual-monitor-main\setup_sunvdm.ps1" %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > "C:\CLI\sunshine-virtual-monitor-main\sunvdm.log" 2>&1 running with PID 24992
[2024:09:13:20:43:52]: Error: A UPnP device has been found,  but it wasn't recognized as an IGD
[2024:09:13:20:46:00]: Error: A UPnP device has been found,  but it wasn't recognized as an IGD
[2024:09:13:20:47:05]: Error: [cmd /C powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\CLI\sunshine-virtual-monitor-main\setup_sunvdm.ps1" %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > "C:\CLI\sunshine-virtual-monitor-main\sunvdm.log" 2>&1] failed with code [1]
```

I then open the sunvdm.log and it has the following:

```
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Setting up a moonlight monitor with 2560x1440@120 with hdr off
Enabling the virtual display.
Get-PnpDevice : Cannot validate argument on parameter 'FriendlyName'. The argument is null. Provide a valid value for 
the argument, and then try running the command again.
At C:\CLI\sunshine-virtual-monitor-main\setup_sunvdm.ps1:72 char:29
+ Get-PnpDevice -FriendlyName $vdd_name | Enable-PnpDevice -Confirm:$fa ...
+                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PnpDevice], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-PnpDevice
 
Setting up the virtual display and disabling other displays.
Disabling all other displays.
Failed to disable all other displays.
At C:\CLI\sunshine-virtual-monitor-main\setup_sunvdm.ps1:112 char:9
+         Throw "Failed to disable all other displays."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to disable all other displays.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to disable all other displays.
```

I have tried enabling and disabling the virtual display through the device manager, but I get the same results. Have you run into this issue before?

**Comment by Cynary** [comment] 2024-09-14 02:07
So, the issue is mainly this one:
```
+ Get-PnpDevice -FriendlyName $vdd_name | Enable-PnpDevice -Confirm:$fa ...
+                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PnpDevice], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-PnpDevice
```

Because of that error it can't setup the virtual display, and windows won't allow dropping all displays.
Need to figure out why `$vdd_name` isn't populated. Not sure why you're seeing the `nvapi64.dll` error, it might be related.
Are you using WIndows 10, or Windows 11?

What is the output of the following commands on a powershell terminal?
```
Get-PnpDevice -Class Display
Get-PnpDevice -Class Display | Where-Object {$_.FriendlyName -like "*idd*" -or $_.FriendlyName -like "*mtt*"}
```

That's what we use to derive the virtual display name. I've tested the `idd` case, since that's the Windows 11 case, but I haven't tested the `mtt` case - that's supposed to match the display on WIndows 10, but I wonder if there could be other names that wouldn't match this pattern? (cc: @LeGeRyChEeSe )

**Comment by gercamjr** [comment] 2024-09-14 17:20
My machine is running Windows 10. I have a dummy plug that I use as a Parsec Virtual Display, a second virtual display I created using the Virtual Display Driver, and my main monitor. So the output of the commands are:

```
PS C:\Users\gera> Get-PnpDevice -Class Display -verbose

Status     Class           FriendlyName                                                                     InstanceId
------     -----           ------------                                                                     ----------
OK         Display         Parsec Virtual Display Adapter                                                   ROOT\DISPLAY...
Error      Display         Virtual Desktop Monitor                                                          ROOT\DISPLAY...
Error      Display         Virtual Display with HDR                                                         ROOT\DISPLAY...
OK         Display         AMD Radeon RX 6900 XT                                                            PCI\VEN_1002...
```

```
PS C:\Users\gera> Get-PnpDevice -Class Display | Where-Object {$_.FriendlyName -like "*idd*" -or $_.FriendlyName -like "*mtt*"}
PS C:\Users\gera>
```

**Comment by Cynary** [comment] 2024-09-15 01:21
Hi, thanks for the info - can you check if the changes in the linked pull request work for you? If so, I'll merge it into master.

**Comment by Cynary** [comment] 2024-09-25 05:08
I merged, since it seemed likely to fix the issue - please update if it didn't.

**Closed** 2024-09-25 05:07 UTC
